config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy


  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: [0,1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
 class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)

    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviewsindex_helper.rb
module ReviewsindexHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<h1>My list of restaurants</h1>
<% @restaurants.each do |restaurant| %>
  <h2><%= restaurant.name %></h2>
  <p><%= restaurant.address %></p>
  <p><%= restaurant.phone_number %></p>
  <p><%= restaurant.category %></p>
<% end %>
  <%= link_to 'show this restaurant', restaurant_path(restaurant) %>
  <%= link_to 'edit', edit_restaurant_path(restaurant)  %>
  <%= link_to 'delete', restaurant_path(article), method: :delete, data: { confirm: "Are you sure?" }  %>

  <%= link_to 'new restaurant', new_restaurant_path  %>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>

<%= simple_form_for [@restaurant, @restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>

  <%= f.submit "validez", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>
<p>Find me in app/views/restaurants/show.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviewsindex#edit</h1>
<p>Find me in app/views/reviewsindex/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviewsindex#new</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
    <%= f.input :rating %>

  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviewsindex#show</h1>
<p>Find me in app/views/reviewsindex/show.html.erb</p>